checkpoint:
  path: "trained_models/whisper_mfcc_specrnet_finetuned/weights.pth"
data:
  seed: 42
model:
  name: whisper_frontend_specrnet
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001
  parameters:
    freeze_encoder: false
    frontend_algorithm:
      - mfcc
    input_channels: 2
